'use strict';
const SETTINGS=[1,2,4,5,6];
const storeKey='monkeyturnv-counter2-state-v1';
const defaults={
  counters:{totalGames:0,normalGames:0,atGames:0,atHits:0,fiveCoins:0,directStrongCherry:0,directStrongChance:0,directOther:0,rivalEnoki:0,rivalGamou:0,rivalHamaoka:0,chargeRare:0,chargeEx:0,sgBlue:0,sgYellow:0,sgBlack:0,trophyBronze:0,trophyGold:0,trophyKerot:0,trophyRainbow:0,ticketSilver:0,ticketGold:0,ticketRainbow:0,voiceOtsukare:0,voiceTeiou:0},
  use:{atHits:true,fiveCoins:false,direct:false,rival:false,charge:false,sg:false,trophy:false,ticket:false,voice:false},
  fiveBase:'totalGames',impact:true
};
let state=load();
const data={
  atHits:{name:'AT初当たり',unit:'確率',base:'normalGames',count:'atHits',impact:3,public:{1:'1/299.8',2:'1/295.5',4:'1/258.8',5:'1/235.7',6:'1/222.9'}},
  fiveCoins:{name:'5枚役',unit:'確率',base:'dynamicFive',count:'fiveCoins',impact:2,public:{1:'1/26.6',2:'1/26.0',4:'1/24.9',5:'1/24.1',6:'1/23.4'}},
  direct:{name:'AT直撃',impact:5,public:{1:'強レア小役0.4% / 弱レア小役なし',2:'強レア小役1.2% / 弱レア小役なし',4:'強レア小役2.0% / 弱レア小役0.4〜0.8%',5:'強レア小役3.9% / 弱レア小役2.0%',6:'強レア小役6.3% / 弱レア小役3.1%'}},
  rival:{name:'ライバルモード',impact:3,public:{1:'トータル30.0%',2:'31.6%',4:'36.3%',5:'41.7%',6:'44.0%'}},
  charge:{name:'激走チャージ',impact:3,public:{1:'ボート25.0% / 弱チェリー31.3%',2:'26.2% / 32.0%',4:'32.8% / 37.5%',5:'39.1% / 40.6%',6:'43.0% / 46.9%'}},
  sg:{name:'SGメダル',impact:2,public:{1:'黒メダル1.3%',2:'1.5%',4:'4.0%',5:'4.5%',6:'4.5%'}},
  trophy:{name:'トロフィー',impact:5,public:{1:'なし',2:'銅=設定2以上',4:'金=設定4以上',5:'ケロット柄=設定5以上',6:'虹=設定6'}},
  ticket:{name:'舟券',impact:5,public:{1:'なし',2:'銀=偶数設定濃厚',4:'金=設定4以上',5:'金=設定4以上',6:'虹=設定6'}},
  voice:{name:'セリフ',impact:4,public:{1:'なし',2:'おつかれ=偶数設定濃厚',4:'艇王セリフ=設定4以上',5:'艇王セリフ=設定4以上',6:'艇王セリフ=設定4以上'}}
};
const counterGroups=[
 ['ホーム',[['総ゲーム数','totalGames'],['通常ゲーム数','normalGames'],['ATゲーム数','atGames']]],['AT初当たり',[['AT初当たり','atHits']]],['5枚役',[['5枚役','fiveCoins']]],['AT直撃',[['強チェリー直撃','directStrongCherry'],['強チャンス目直撃','directStrongChance'],['その他直撃','directOther']]],['ライバルモード',[['榎木モード','rivalEnoki'],['蒲生モード','rivalGamou'],['浜岡モード','rivalHamaoka']]],['激走チャージ',[['レア小役成立','chargeRare'],['EXアイテム獲得','chargeEx']]],['レア小役',[]],['SGメダル',[['青メダル','sgBlue'],['黄メダル','sgYellow'],['黒メダル','sgBlack']]],['トロフィー',[['銅トロフィー','trophyBronze'],['金トロフィー','trophyGold'],['ケロット柄トロフィー','trophyKerot'],['虹トロフィー','trophyRainbow']]],['舟券',[['銀舟券','ticketSilver'],['金舟券','ticketGold'],['虹舟券','ticketRainbow']]],['セリフ',[['おつかれ','voiceOtsukare'],['艇王セリフ','voiceTeiou']]]
];
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(storeKey)||'{}')}}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(storeKey,JSON.stringify(state))}
function inc(k,d){state.counters[k]=Math.max(0,(state.counters[k]||0)+d);save();render()}
function ratio(count,base){return count>0&&base>0?base/count:0}
function nearest(v,publicObj){if(!v)return '未入力';let best=SETTINGS[0],diff=1e9;for(const s of SETTINGS){const n=parseFloat(String(publicObj[s]).match(/[\d.]+/)?.[0]);if(n){const d=Math.abs(v-n);if(d<diff){diff=d;best=s}}}return `設定${best}近似値`}
function stars(n){return '★★★★★'.slice(0,n)+'☆☆☆☆☆'.slice(0,5-n)}
function confirmations(){let min=1,only=null,deny=new Set(),texts=[];const c=state.counters;if(c.trophyBronze>0){min=Math.max(min,2);texts.push('設定2以上確定（銅トロフィー）')}if(c.trophyGold>0){min=Math.max(min,4);texts.push('設定4以上確定（金トロフィー）')}if(c.trophyKerot>0){min=Math.max(min,5);texts.push('設定5以上確定（ケロット柄トロフィー）')}if(c.trophyRainbow>0){only=6;texts.push('設定6確定（虹トロフィー）')}if(c.ticketSilver>0){deny.add(1);deny.add(5);texts.push('偶数設定確定（銀舟券）')}if(c.ticketGold>0){min=Math.max(min,4);texts.push('設定4以上確定（金舟券）')}if(c.ticketRainbow>0){only=6;texts.push('設定6確定（虹舟券）')}if(c.voiceOtsukare>0){deny.add(1);deny.add(5);texts.push('偶数設定確定（おつかれ）')}if(c.voiceTeiou>0){min=Math.max(min,4);texts.push('設定4以上確定（艇王セリフ）')}if(c.directOther>0){min=Math.max(min,4);texts.push('設定4以上確定（弱レア小役直撃）')}return{min,only,deny,texts}}
function weights(){let w={1:1,2:1,4:1,5:1,6:1};const c=state.counters;const conf=confirmations();if(state.use.atHits){const r=ratio(c.atHits,c.normalGames||c.totalGames);if(r) SETTINGS.forEach(s=>w[s]*=1/(Math.abs(r-parseFloat(data.atHits.public[s].slice(2)))+8))}if(state.use.fiveCoins){const base=state.fiveBase==='normalGames'?c.normalGames:c.totalGames;const r=ratio(c.fiveCoins,base);if(r) SETTINGS.forEach(s=>w[s]*=1/(Math.abs(r-parseFloat(data.fiveCoins.public[s].slice(2)))+1.8))}if(state.use.direct){w[4]+=c.directStrongCherry*1.8+c.directStrongChance*2.2+c.directOther*8;w[5]+=c.directStrongCherry*3.4+c.directStrongChance*4.2+c.directOther*12;w[6]+=c.directStrongCherry*5.5+c.directStrongChance*6.5+c.directOther*15}
if(state.use.rival){w[5]+=c.rivalGamou*.4;w[6]+=c.rivalGamou*.5;w[4]+=c.rivalEnoki*.2+c.rivalHamaoka*.2}
if(state.use.charge&&c.chargeRare>0){const p=c.chargeEx/c.chargeRare;w[4]+=p*2;w[5]+=p*3;w[6]+=p*4}
for(const s of SETTINGS){if(conf.only&&s!==conf.only)w[s]=0;if(s<conf.min)w[s]=0;if(conf.deny.has(s))w[s]=0}if(conf.only)w[conf.only]=999;return w}
function percents(){const w=weights();let sum=SETTINGS.reduce((a,s)=>a+w[s],0)||1;let p={};SETTINGS.forEach(s=>p[s]=w[s]<=0?0:Math.max(1,Math.round(w[s]/sum*100)));let total=SETTINGS.reduce((a,s)=>a+p[s],0);while(total>100){let k=SETTINGS.filter(s=>p[s]>1).sort((a,b)=>p[b]-p[a])[0]; if(!k)break;p[k]--;total--}while(total<100){let k=SETTINGS.sort((a,b)=>p[b]-p[a])[0];p[k]++;total++}return p}
function renderJudgment(){const p=percents();oddsBars.innerHTML=SETTINGS.map(s=>`<div class="odds-line"><b>設定${s}</b><div class="bar-track"><div class="bar-fill" style="width:${p[s]}%"></div></div><b>${p[s]}%</b></div>`).join('');const conf=confirmations();confirmList.className=conf.texts.length?'confirm-list':'confirm-list muted';confirmList.innerHTML=conf.texts.length?conf.texts.map(t=>`<span class="confirm-pill">${t}</span>`).join(''):'確定・否定なし';judgeItems.innerHTML=Object.entries(data).map(([id,d])=>judgeItem(id,d)).join('')}
function itemSummary(id,d){const c=state.counters;let v=0,txt='未入力';if(id==='atHits'){v=ratio(c.atHits,c.normalGames||c.totalGames);txt=v?`1/${v.toFixed(1)}（${nearest(v,d.public)}）`:'未入力'}else if(id==='fiveCoins'){const b=state.fiveBase==='normalGames'?c.normalGames:c.totalGames;v=ratio(c.fiveCoins,b);txt=v?`1/${v.toFixed(1)}（${nearest(v,d.public)}）`:'未入力'}else if(id==='direct'){txt=`強チェリー${c.directStrongCherry} / 強チャンス目${c.directStrongChance} / その他${c.directOther}`}else if(id==='rival'){txt=`榎木${c.rivalEnoki} / 蒲生${c.rivalGamou} / 浜岡${c.rivalHamaoka}`}else if(id==='charge'){txt=`${c.chargeEx}/${c.chargeRare}`}else if(id==='sg'){txt=`青${c.sgBlue} / 黄${c.sgYellow} / 黒${c.sgBlack}`}else if(id==='trophy'){txt=`銅${c.trophyBronze} / 金${c.trophyGold} / ケロット${c.trophyKerot} / 虹${c.trophyRainbow}`}else if(id==='ticket'){txt=`銀${c.ticketSilver} / 金${c.ticketGold} / 虹${c.ticketRainbow}`}else if(id==='voice'){txt=`おつかれ${c.voiceOtsukare} / 艇王${c.voiceTeiou}`}return txt}
function judgeItem(id,d){const pub=Object.entries(d.public).map(([s,v])=>`<tr><td>設定${s}</td><td>${v}</td></tr>`).join('');const five=id==='fiveCoins'?`<div class="radio-row"><label><input type="radio" name="fiveBase" value="totalGames" ${state.fiveBase==='totalGames'?'checked':''}> 総ゲーム数</label><label><input type="radio" name="fiveBase" value="normalGames" ${state.fiveBase==='normalGames'?'checked':''}> 通常ゲーム数</label></div>`:'';return `<div class="judge-item" data-id="${id}"><div class="judge-head"><input class="use-check" type="checkbox" ${state.use[id]?'checked':''}><div><div class="judge-title">${d.name}</div><div class="judge-summary">${itemSummary(id,d)}</div>${state.impact?`<div class="impact">${stars(d.impact)}</div>`:''}</div><button class="mini" type="button">▼</button></div><div class="judge-detail">${five}<div class="public-values"><h4>公表値</h4><table>${pub}</table></div></div></div>`}
function renderCounters(){counterCards.innerHTML='';const tpl=counterTemplate;counterGroups.forEach(([title,rows])=>{const node=tpl.content.cloneNode(true);const card=node.querySelector('.card');node.querySelector('.card-title').textContent=title;const body=node.querySelector('.collapsible');body.innerHTML=rows.length?rows.map(([label,key])=>`<div class="counter-row"><span>${label}</span><span class="value">${state.counters[key]||0}</span><span class="counter-actions"><button data-inc="${key}">＋</button><button class="ghost" data-dec="${key}">－</button></span></div>`).join(''):'<p class="note">現在は判別表示用の項目です。必要に応じてカウント項目を追加できます。</p>';counterCards.appendChild(node)})}
function render(){renderJudgment();renderCounters();document.getElementById('impactToggle').checked=state.impact}
document.addEventListener('click',e=>{const t=e.target;if(t.closest('.card-toggle')){t.closest('.card').classList.toggle('open')}if(t.dataset.inc)inc(t.dataset.inc,1);if(t.dataset.dec)inc(t.dataset.dec,-1);if(t.id==='useAllBtn'){Object.keys(state.use).forEach(k=>state.use[k]=true);save();render()}if(t.id==='clearAllBtn'){Object.keys(state.use).forEach(k=>state.use[k]=false);save();render()}if(t.id==='resetAllBtn'&&confirm('すべてリセットしますか？')){state=structuredClone(defaults);save();render()}if(t.closest('.judge-head')&&!t.classList.contains('use-check'))t.closest('.judge-item').classList.toggle('open')});
document.addEventListener('change',e=>{const t=e.target;if(t.classList.contains('use-check')){state.use[t.closest('.judge-item').dataset.id]=t.checked;save();render()}if(t.name==='fiveBase'){state.fiveBase=t.value;save();render()}if(t.id==='impactToggle'){state.impact=t.checked;save();render()}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});
render();
